theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    footer: "/assets/images/logof.svg"
  summary:
    position: content
  search:
    active: false
  programs:
    related_posts:
      quantity: 3
  blocks:
    testimonials:
      splide:
        arrows: true
        autoplay: true
        pauseOnHover: false
        pauseOnFocus: true
        type: loop
        autoHeight: true
        interval: 8000
  debug:
     productionUrl: "https://master-class.mathieujahnich.osuny.site/"